spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/wechat?Unicode=true&characterEncoding=UTF-8&serverTimezone=UTC
     username: root
     password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
        show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
     max-file-size: 500MB
     max-request-size: 500MB